# Since we use custom test script, disable the default build action
build: false


# The Rust target platforms
platform:
  - rp2040-picow


# The Rust config matrix
configuration:
  - --features=


# General environment vars
environment:
  # Promote warnings to errors
  RUSTFLAGS: -D warnings


# Fail fast if one job in the matrix fails
matrix:
  fast_finish: true


# Build library
for:
  # - matrix:
  #     only:
  #       - platform: rp2040-picow
  - environment:
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      RUST_TARGET: thumbv6m-none-eabi
    install:
      - curl https://sh.rustup.rs -sSf -o rustup-init.sh
      - sh rustup-init.sh -y --default-host x86_64-unknown-linux-gnu
      - source $HOME/.cargo/env
      - rustup target add "$RUST_TARGET"
    test_script:
      # Only build as we do not emulate the microcontroller to really run the code
      - cd "$PLATFORM" && cargo build --verbose --no-default-features $CONFIGURATION
      - cd "$PLATFORM" && cargo build --verbose --release --no-default-features $CONFIGURATION
