# Since we use custom test script, disable the default build action
build: false


# General environment vars
environment:
  RUSTFLAGS: -D warnings
  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  matrix:
    - FIRMWARE: rp2040-picow
      TARGET: thumbv6m-none-eabi
    - FIRMWARE: rp2350-pico2w
      TARGET: thumbv8m.main-none-eabihf


# Fail fast if one job in the matrix fails
matrix:
  fast_finish: true


# Build app
for:
  - install:
      - curl https://sh.rustup.rs -sSf -o rustup-init.sh
      - sh rustup-init.sh -y --default-host x86_64-unknown-linux-gnu
      - source $HOME/.cargo/env
      - rustup target add "$TARGET"
      - cargo install flip-link
    test_script:
      # Only build as we do not emulate the microcontroller to really run the code
      - cd "$FIRMWARE" 
      - cargo build --verbose
      - cargo build --verbose --release
